name: tiki_sdk_js
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  html: ^0.15.1
  http: ^0.13.5
  js: ^0.6.7
  sqlite3: ^1.10.1
  tiki_sdk_dart:
    path: ../tiki-sdk-dart
